name: Code Style Check

on:
  push:
    branches: [develop]

jobs:
  lint:
    name: Check prettier and eslint
    runs-on: ubuntu-latest
    env:
      NODE_AUTH_TOKEN: ${{ secrets.RELEASE_GITHUB_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install node.js v16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          scope: '@hitechline'
          registry-url: 'https://npm.pkg.github.com'

      - name: Install dependencies
        run: npm install --no-package-lock

      - name: Check prettier
        run: npm run format

      - name: Check eslint
        run: npm run lint
